---
#playbook.yaml

- name: DISPLAY THE INVENTORY VARS
  hosts: localhost # These are dynamically generated groups from the plugin
  gather_facts: no
  tasks:
    - name: DISPLAY THE HOST VARS
      debug:
        msg: "The mgmt IP is {{ ansible_host }}"
